# Site settings
title: "GigaTech"
description: > # this means to ignore newlines until "baseurl:"
  GigaTech is an HTML5 game engine written in CoffeeScript.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gigacorp.github.com/GigaTech" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
